### ISSUE TITLE
[PLAN] Consider Rust

### ISSUE THREAD

**Issue by abebeos** [deepnest-io/Deepnest#174]
* pro/cons of using RUST for some of the modules

**Comment by Dexus** [comment]
**Pro:**

- Rust would be nice because we would be able to switch to tauri v2 if electron is going more the way of incompatible to nodejs.

- Rust is safe, no memory leaks for pure rust libs. Also bring more core functions to rust would be bring us the benefit to use more memory when need. Because electon is only give us 4GB ram once we use modules we can use more.

- Native code is faster!

What else you need?

**Cons:**

- Less javascript/typescript and more rust code

- rust knowledge need - so not at all beginner friendly

**Comment by abebeos** [comment]
Let's agree for now to keep it minimal. Any decent C++ programmer should have the brains to use rust, but initially, you alone would be the maintainer of rust modules/code.

Once we've stabilized this thing, then I would be fine to move this even 100% to rust.
