### ISSUE TITLE
[RFA] Provide Offline DXF Conversion

### ISSUE THREAD

**Issue by ghost** [deepnest-io/Deepnest#54]
(sponsored by @dorkmo )
(RFA - requirements/feasibility analysis)

## Status

Local deepnest depends on deepnest.io for DXF conversion

## Expected

DXF conversion can be done locally, offline.

### Depends On

(need to be solved first, in order to keep the overall DXF implementation effort low. This is to avoid "evolving spaghetti-code")

- [x] #83
- [ ] (possibly) #87
- [ ] (possibly) #66
- [ ] (possibly) #67

### DXF Itself

- [ ] Provide Server-Independent DXF Import
- [ ] Provide Server-Independent DXF Export

## Requirements & Feasibility

- Assessing feasibility should be done after further evolving the code first (see "Depends On above")
- Possibly better to spawn an independent task (e.g. "Try SVG->DXF conversion tools for use with Deepnest")
  - this would enable parallel work (dev A goes on with "Depends On", dev B executes the conversion trials)

**Comment by abebeos** [comment]
> draft

**Comment by abebeos** [comment]
@dorkmo , hi there!

As you possibly know, bountysource stopped paying out bounty-workers since early this year

https://github.com/bountysource/core/issues/1586

The bountysource app is down since mid Sep. 2023

https://app.bountysource.com/issues/120217906-building-with-vs2022-under-windows-11

### Paypal Buyer Protection

Though you got the service from me, I did not receive the payment, bountysource has kept the money.

You are now eligible for paypal buyer protection (others have gone successfully this path) :

https://github.com/bountysource/core/issues/1586#issuecomment-1732668211

If you could do this, and pay me directly, you could keep the 10% for your efforts.

Thank you.
